# Project information
site_name: 'ISCC - Content Codes'
site_description: 'International Standard Content Code - Specification'
site_author: 'Titusz Pan'
site_url: 'http://iscc.codes'

# Repository
repo_name: 'iscc/iscc-specs'
repo_url: 'https://github.com/iscc/iscc-specs'
edit_uri: 'edit/master/docs/'

# Copyright
copyright: 'Copyright © 2016-2022 The Authors
| <a href="https://iscc.foundation/privacy">Privacy Policy</a>
| <a href="https://iscc.foundation/cookies">Cookie Policy</a>
| <a href="https://iscc.foundation/imprint">Imprint</a>
| <a href="https://iscc.foundation/disclaimer">Disclaimer</a>'

theme:
    name: material
    custom_dir: overrides
    language: en
    logo: images/logo-white.svg
    favicon: images/favicon.png
    palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    features:
    # - toc.integrate
    - navigation.indexes
    - navigation.tracking
    # -  navigation.tabs
    # - navigation.tabs.sticky
    - navigation.expand

#    features:
#        - navigation.tabs
#        - navigation.tabs.sticky
#        - navication.sections
#        - toc.integrate

extra_css:
  - stylesheets/custom.css

nav:
    - Overview: 'index.md'
    - Features: 'features.md'
    - Concept: 'concept.md'
    - Specification: 'specification.md'
    - Resources: 'resources.md'
    - Versions:
          - Version 1.x: 'specification.md'
          - Version 1.0: 'https://github.com/iscc/iscc-specs/blob/version-1.0/docs/specification.md'
    - License: 'license.md'

extra:
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/iscc
        - icon: fontawesome/brands/telegram
          link: https://t.me/iscc_dev
        - icon: fontawesome/brands/twitter
          link: https://twitter.com/iscc_foundation

markdown_extensions:
    - abbr
    - admonition
    - attr_list
    - def_list
    - footnotes
    - meta
    - toc:
          permalink: "#"
    - pymdownx.highlight
    - pymdownx.superfences
    - pymdownx.magiclink

plugins:
    - search
    - git-revision-date-localized:
          type: iso_datetime
    - minify:
          minify_html: true
    - redirects:
          redirect_maps:
              'implementations.md': resources.md

